name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: washed

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies service
        run: |
          npm i
      - name: Running tests
        run: npm test

      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: AKIAXNQDEYLLSEDRJ66Q
          aws_secret_access_key: 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
          aws_region: eu-west-1
          zip_file: bundle.zip
